---
name: Submit Dependencies

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    name: 'Submit Dependencies'
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            java:
              version: '11'
            gradle:
              version: 'wrapper'
              command: './gradlew'  # Workaround for issue https://github.com/gradle/actions/issues/273
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Validate Gradle wrapper'
        uses: gradle/actions/wrapper-validation@v4
      - name: "Setup JDK temurin ${{ matrix.java.version }}"
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java.version }}
          distribution: temurin
      - name: 'Generate and submit dependency graph'
        uses: gradle/actions/dependency-submission@v4
        with:
          gradle-version: ${{ matrix.gradle.version }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
